-- # Includes highlights for - https://github.com/vim-python/python-syntax
-- pythonStatement: '' # Statement
-- pythonConditional: '' # Conditional
-- pythonRepeat: '' # Repeat
-- pythonOperator: '' # Operator
-- pythonException: '' # Exception
-- pythonInclude: '' # Include
-- pythonDecorator: '' # Define
-- pythonFunction: '' # Function
-- pythonComment: '' # Comment
-- pythonTodo: '' # Todo
-- pythonString: '' # String
-- pythonRawString: '' # String
-- pythonQuotes: '' # String
-- pythonTripleQuotes: '' # pythonQuotes
-- pythonEscape: '' # Special
-- pythonNumber: '' # Number
-- pythonBuiltin: '@Builtin' # Function
-- pythonExceptions: '' # Structure
-- # pythonSpaceError: '' # Error - defined below
-- pythonDoctest: '' # Special
-- pythonDoctestValue: '' # Define
-- pythonDecoratorName: '@pythonDecorator'

-- # vim-python/python-syntax plugin
-- pythonFunctionCall: '@pythonFunction'
-- pythonDottedName: '@pythonDecorator'
-- pythonDot: '@Noise'

-- pythonHexNumber: '@Float'
-- pythonOctNumber: '@Float'
-- pythonBinNumber: '@Float'

-- pythonNull: '@Constant'
-- pythonBoolean: '@Boolean'
-- pythonSingleton: '@pythonNull'
-- pythonBuiltInFunc: '@pythonBuiltin'
-- pythonBuiltinObj: '@pythonNull'
-- pythonBuiltinType: '@Structure'

-- pythonError: '@DiffDelete'
-- pythonIndentError: '@pythonError'
-- pythonSpaceError: '@DiffText'
-- pythonUniEscapeError: '@pythonError'
-- pythonUniRawEscapeError: '@pythonError'
-- pythonBytesError: '@pythonError'
-- pythonBytesEscapeError: '@pythonError'
-- pythonNumberError: '@pythonError'
-- pythonOctError: '@pythonError'
-- pythonHexError: '@pythonError'
-- pythonBinError: '@pythonError'

