
local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#c5c8c6", bg = "#111112"},
Builtin = {fg = "#00bcbc"},
["@attribute.builtin"] = {link = "Builtin"},
["@function.builtin"] = {link = "Builtin"},
["@type.builtin"] = {link = "Builtin"},
CmpItemAbbrMatch = {fg = "#c5c8c6"},
CmpItemAbbrMatchFuzzy = {fg = "#4f5462"},
CmpItemKind = {fg = "#5f4448"},
CmpItemMenu = {fg = "#4e432f"},
ColorColumn = {bg = "#141415"},
Comment = {fg = "#4f5462"},
StartifyBracket = {link = "Comment"},
StartifyPath = {link = "Comment"},
StartifySlash = {link = "Comment"},
TelescopeNormal = {link = "Comment"},
["@tag.delimiter"] = {link = "Comment"},
Conceal = {bg = "#2c2e34"},
Constant = {fg = "#d185b3"},
Boolean = {link = "Constant"},
Label = {link = "Constant"},
["@markup.math"] = {link = "Constant"},
CursorColumn = {bg = "#141415"},
CursorLine = {bg = "#141415"},
CursorLineNr = {fg = "#7eb2dd"},
DiagnosticError = {fg = "#ff3d5b"},
DiagnosticHint = {fg = "#9c8cc3"},
DiagnosticInfo = {fg = "#7eb2dd"},
DiagnosticSignError = {fg = "#ff3d5b", bg = "#141415"},
DiagnosticSignHint = {fg = "#9c8cc3", bg = "#141415"},
DiagnosticSignInfo = {fg = "#7eb2dd", bg = "#141415"},
DiagnosticSignWarn = {fg = "#f39660", bg = "#141415"},
DiagnosticUnderlineError = {fg = "#ff3d5b", bg = "#5f4448", undercurl = true},
DiagnosticUnderlineHint = {fg = "#9c8cc3", bg = "#242b36", undercurl = true},
DiagnosticUnderlineInfo = {fg = "#7eb2dd", bg = "#242b36", undercurl = true},
DiagnosticUnderlineWarn = {fg = "#f39660", bg = "#4e432f", undercurl = true},
DiagnosticWarn = {fg = "#f39660"},
DiffAdd = {fg = "#83d28d", bg = "#43634e"},
["@diff.plus"] = {link = "DiffAdd"},
DiffChange = {fg = "#4f5462", bg = "#242b36"},
DiffDelete = {fg = "#ff3d5b", bg = "#5f4448"},
["@diff.minus"] = {link = "DiffDelete"},
DiffText = {fg = "#f39660", bg = "#4e432f"},
["@diff.delta"] = {link = "DiffText"},
Directory = {fg = "#7eb2dd"},
Error = {fg = "#ff3d5b", bg = "#242b36"},
["@comment.error"] = {link = "Error"},
ErrorMsg = {fg = "#ff3d5b"},
Float = {fg = "#b1d072"},
FoldColumn = {bg = "#141415"},
Folded = {fg = "#7eb2dd", bg = "#2c2e34"},
Function = {fg = "#7eb2dd"},
StartifyFile = {link = "Function"},
GitSignsAdd = {fg = "#83d28d", bg = "#141415"},
GitGutterAdd = {link = "GitSignsAdd"},
GitSignsChange = {fg = "#f39660", bg = "#141415"},
GitGutterChange = {link = "GitSignsChange"},
GitSignsChangeDelete = {fg = "#f0c674", bg = "#141415"},
GitGutterChangeDelete = {link = "GitSignsChangeDelete"},
GitSignsDelete = {fg = "#fc5d7c", bg = "#141415"},
GitGutterDelete = {link = "GitSignsDelete"},
Identifier = {fg = "#7dc3bd"},
StartifyFooter = {link = "Identifier"},
StartifyHeader = {link = "Identifier"},
["@markup.heading.2"] = {link = "Identifier"},
["@markup.heading.3"] = {link = "Identifier"},
["@markup.heading.4"] = {link = "Identifier"},
["@markup.heading.5"] = {link = "Identifier"},
["@markup.heading.6"] = {link = "Identifier"},
["@tag.attribute"] = {link = "Identifier"},
["@variable.member"] = {link = "Identifier"},
["@variable.parameter"] = {link = "Identifier"},
Ignore = {fg = "#33353f"},
IncSearch = {fg = "#111112", bg = "#f39660"},
CurSearch = {link = "IncSearch"},
["@markup.list"] = {link = "Keyword"},
["@markup.quote"] = {link = "Label"},
LineNr = {fg = "#4f5462", bg = "#141415"},
["@constant.macro"] = {link = "Macro"},
["@function.macro"] = {link = "Macro"},
MatchParen = {fg = "#111112", bg = "#7eb2dd"},
ModeMsg = {fg = "#56eded"},
MoreMsg = {fg = "#83d28d"},
Noise = {fg = "#7f8490"},
["@punctuation.bracket"] = {link = "Noise"},
["@punctuation.delimiter"] = {link = "Noise"},
["@string.documentation"] = {link = "Noise"},
NonText = {fg = "#33353f"},
NormalFloat = {fg = "#c5c8c6", bg = "#010102"},
NormalNC = {fg = "#4f5462", bg = "#111112"},
Number = {fg = "#83d28d"},
["@markup.list.checked"] = {link = "Number"},
Operator = {fg = "#f39660"},
Delimiter = {link = "Operator"},
Pmenu = {fg = "#4f5462", bg = "#25262c"},
PmenuSbar = {bg = "#2c2e34"},
PmenuSel = {fg = "#111112", bg = "#7eb2dd"},
PmenuThumb = {bg = "#4f5462"},
PreProc = {fg = "#83d28d"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
Question = {fg = "#f39660"},
Search = {fg = "#111112", bg = "#f0c674"},
SignColumn = {bg = "#141415"},
Special = {fg = "#9c8cc3"},
Debug = {link = "Special"},
GitSignsUntracked = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@module"] = {link = "Special"},
SpecialKey = {fg = "#9c8cc3"},
SpellBad = {fg = "#fc5d7c", italic = true, undercurl = true},
SpellCap = {fg = "#f39660", italic = true, undercurl = true},
SpellLocal = {fg = "#f0c674", italic = true, undercurl = true},
SpellRare = {fg = "#7eb2dd", italic = true, undercurl = true},
Statement = {fg = "#fc5d7c"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Repeat = {link = "Statement"},
["@punctuation.special.markdown"] = {link = "Statement"},
["@tag.builtin"] = {link = "Statement"},
StatusLine = {fg = "#4f5462", bg = "#141415"},
StatusLineDefault = {fg = "#111112", bg = "#7dc3bd"},
StatusLineFlag = {fg = "#f39660", bg = "#141415"},
StatusLineHighlight = {fg = "#56eded", bg = "#141415"},
StatusLineInsert = {fg = "#111112", bg = "#7eb2dd"},
StatusLineMid = {fg = "#7f8490", bg = "#2c2e34"},
StatusLineMidBlue = {fg = "#7eb2dd", bg = "#2c2e34"},
StatusLineMidGreen = {fg = "#83d28d", bg = "#2c2e34"},
StatusLineMidOrange = {fg = "#f39660", bg = "#2c2e34"},
StatusLineMidPurple = {fg = "#9c8cc3", bg = "#2c2e34"},
StatusLineMidRed = {fg = "#fc5d7c", bg = "#2c2e34"},
StatusLineNC = {fg = "#4f5462", bg = "#25262c"},
StatusLineNCLight = {fg = "#33353f", bg = "#2c2e34"},
StatusLineNCMid = {fg = "#4f5462", bg = "#2c2e34"},
StatusLineNCRedFlag = {fg = "#fc5d7c", bg = "#25262c"},
StatusLineNormal = {fg = "#111112", bg = "#fc5d7c"},
StatusLineRedFlag = {fg = "#fc5d7c", bg = "#141415"},
StatusLineReplace = {fg = "#111112", bg = "#9c8cc3"},
StatusLineTabModifiedActive = {fg = "#5f4448", bg = "#2c2e34"},
StatusLineTabModifiedCurrent = {fg = "#fc5d7c", bg = "#242b36"},
StatusLineTabModifiedHidden = {fg = "#5f4448", bg = "#010102"},
StatusLineVisual = {fg = "#111112", bg = "#f39660"},
String = {fg = "#f0c674"},
Character = {link = "String"},
Substitute = {fg = "#f39660", bg = "#242b36"},
TabLine = {fg = "#4f5462", bg = "#010102"},
StatusLineTabHidden = {link = "TabLine"},
TabLineFill = {fg = "#4f5462", bg = "#141415"},
StatusLineTabActive = {link = "TabLineFill"},
TabLineSel = {fg = "#56eded", bg = "#242b36"},
StatusLineTabCurrent = {link = "TabLineSel"},
TelescopeBorder = {fg = "#4f5462"},
TelescopeMatching = {fg = "#7dc3bd"},
TelescopePromptPrefix = {fg = "#4f5462"},
TelescopeSelection = {bg = "#242b36"},
TelescopeSelectionCaret = {fg = "#56eded"},
Title = {fg = "#56eded"},
Todo = {fg = "#f39660", bg = "#242b36"},
["@comment.warning"] = {link = "Todo"},
Type = {fg = "#56eded"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
Underlined = {fg = "#7dc3bd", underline = true},
VertSplit = {fg = "#25262c"},
Visual = {bg = "#414550"},
VisualNOS = {bg = "#7f8490"},
WarningMsg = {fg = "#f39660"},
StartifyNumber = {link = "WarningMsg"},
Whitespace = {fg = "#5f4448"},
["@string.escape"] = {link = "Whitespace"},
WildMenu = {fg = "#111112", bg = "#7eb2dd"},
floatBorder = {fg = "#33353f", bg = "#111112"},
["@comment.note"] = {fg = "#7eb2dd", bg = "#242b36"},
["@lsp.mod.defaultLibrary"] = {link = "@function.builtin"},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='asteroid'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end

-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
--
-- This isn't strictly required but it can be a useful trick if you are
-- incrementally editing your config a lot and want to be sure your themes
-- changes are being picked up without restarting neovim.
--
-- Note if you're working in on your theme and have :Lushify'd the buffer,
-- your changes will be applied with our without the following line.
--
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
-- package.loaded['lush_theme.asteroid'] = nil

-- include our theme file and pass it to lush to apply
-- require('lush')(require('lush_theme.asteroid'))
