
local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#C5C9C6", bg = "#19191A"},
TSVariable = {link = "Normal"},
["@variable"] = {link = "Normal"},
ALEInfo = {fg = "#7EB2DD", bg = "#252C37"},
pythonBoolean = {link = "Boolean"},
yamlBool = {link = "Boolean"},
Builtin = {fg = "#00BDBD"},
TSFuncBuiltin = {link = "Builtin"},
TSVariableBuiltin = {link = "Builtin"},
htmlH3 = {link = "Builtin"},
javaScriptGlobal = {link = "Builtin"},
javaScriptMember = {link = "Builtin"},
jinjaBlockName = {link = "Builtin"},
jinjaFilter = {link = "Builtin"},
pythonBuiltin = {link = "Builtin"},
["@function.builtin"] = {link = "Builtin"},
["@variable.builtin"] = {link = "Builtin"},
CmpItemAbbrMatch = {fg = "#C5C9C6"},
CmpItemAbbrMatchFuzzy = {fg = "#4F5563"},
CmpItemKind = {fg = "#5F4448"},
CmpItemMenu = {fg = "#504530"},
ColorColumn = {bg = "#1B1B1D"},
Comment = {fg = "#4F5563"},
CtrlPBufferPath = {link = "Comment"},
StartifyBracket = {link = "Comment"},
StartifyPath = {link = "Comment"},
StartifySlash = {link = "Comment"},
TelescopeNormal = {link = "Comment"},
Conceal = {bg = "#2D2F34"},
Constant = {fg = "#D185B2"},
Boolean = {link = "Constant"},
CtrlPPrtText = {link = "Constant"},
Label = {link = "Constant"},
TSConstBuiltin = {link = "Constant"},
TSMath = {link = "Constant"},
htmlSpecialTagName = {link = "Constant"},
javaScriptConstant = {link = "Constant"},
javaScriptNull = {link = "Constant"},
jsonNull = {link = "Constant"},
pythonNull = {link = "Constant"},
yamlTimestamp = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
["@text.math"] = {link = "Constant"},
CtrlPLinePre = {fg = "#54EDED"},
CtrlPMatch = {fg = "#54EDED", bg = "#252C37"},
CtrlPMode1 = {fg = "#F3945E", bg = "#1B1B1D"},
CtrlPMode2 = {fg = "#19191A", bg = "#7EC4BE"},
CursorColumn = {bg = "#25262C"},
CursorLine = {bg = "#25262C"},
CursorLineNr = {fg = "#4F5563"},
pythonDecorator = {link = "Define"},
DiagnosticError = {fg = "#FF3D5A"},
DiagnosticHint = {fg = "#9D8DC3"},
DiagnosticInfo = {fg = "#7EB2DD"},
DiagnosticSignError = {fg = "#FF3D5A", bg = "#1B1B1D"},
DiagnosticSignHint = {fg = "#9D8DC3", bg = "#1B1B1D"},
DiagnosticSignInfo = {fg = "#7EB2DD", bg = "#1B1B1D"},
DiagnosticSignWarn = {fg = "#F3945E", bg = "#1B1B1D"},
DiagnosticUnderlineError = {fg = "#FF3D5A", bg = "#5F4448", undercurl = true},
DiagnosticUnderlineHint = {fg = "#9D8DC3", bg = "#252C37", undercurl = true},
DiagnosticUnderlineInfo = {fg = "#7EB2DD", bg = "#252C37", undercurl = true},
DiagnosticUnderlineWarn = {fg = "#F3945E", bg = "#504530", undercurl = true},
DiagnosticWarn = {fg = "#F3945E"},
DiffAdd = {fg = "#83D28E", bg = "#44644F"},
DiffChange = {fg = "#4F5563", bg = "#252C37"},
DiffDelete = {fg = "#FF3D5A", bg = "#5F4448"},
ALEError = {link = "DiffDelete"},
YcmErrorSection = {link = "DiffDelete"},
DiffText = {fg = "#F3945E", bg = "#504530"},
ALEWarning = {link = "DiffText"},
YcmWarningSectio = {link = "DiffText"},
javaScriptDeprecated = {link = "DiffText"},
pythonSpaceError = {link = "DiffText"},
Directory = {fg = "#7EB2DD"},
ALEInfoSign = {link = "Directory"},
Error = {fg = "#FF3D5A", bg = "#252C37"},
ALEErrorSign = {link = "Error"},
CtrlPBufferCurMod = {link = "Error"},
CtrlPBufferHidMod = {link = "Error"},
CtrlPBufferVisMod = {link = "Error"},
TSDanger = {link = "Error"},
YcmErrorSign = {link = "Error"},
javaScriptError = {link = "Error"},
jsonCommentError = {link = "Error"},
jsonError = {link = "Error"},
jsonMissingCommaError = {link = "Error"},
jsonNoQuotesError = {link = "Error"},
jsonNumError = {link = "Error"},
jsonSemicolonError = {link = "Error"},
jsonStringSQError = {link = "Error"},
jsonTrailingCommaError = {link = "Error"},
jsonTripleQuotesError = {link = "Error"},
pythonError = {link = "Error"},
yamlReservedDirective = {link = "Error"},
ErrorMsg = {fg = "#FF3D5A"},
Float = {fg = "#B0D071"},
pythonBinNumber = {link = "Float"},
pythonHexNumber = {link = "Float"},
pythonOctNumber = {link = "Float"},
FoldColumn = {bg = "#1B1B1D"},
Folded = {fg = "#7EB2DD", bg = "#2D2F34"},
Function = {fg = "#7EB2DD"},
StartifyFile = {link = "Function"},
TSTagAttribute = {link = "Function"},
cssAttr = {link = "Function"},
cssFunction = {link = "Function"},
cssFunctionName = {link = "Function"},
htmlArg = {link = "Function"},
pythonFunction = {link = "Function"},
GitGutterAdd = {fg = "#83D28E", bg = "#1B1B1D"},
GitGutterChange = {fg = "#F3945E", bg = "#1B1B1D"},
GitGutterChangeDelete = {fg = "#E7C665", bg = "#1B1B1D"},
GitGutterDelete = {fg = "#FC5F7E", bg = "#1B1B1D"},
Identifier = {fg = "#7EC4BE"},
StartifyFooter = {link = "Identifier"},
StartifyHeader = {link = "Identifier"},
cssProp = {link = "Identifier"},
jsDestructuringArray = {link = "Identifier"},
jsDestructuringBlock = {link = "Identifier"},
jsModuleKeyword = {link = "Identifier"},
jsObjectKey = {link = "Identifier"},
jsVariableDef = {link = "Identifier"},
yamlTagHandle = {link = "Identifier"},
yamlTagPrefix = {link = "Identifier"},
Ignore = {fg = "#32343E"},
IncSearch = {fg = "#19191A", bg = "#F3945E"},
["@punctuation.special.markdown"] = {link = "Keyword"},
LineNr = {fg = "#32343E", bg = "#1B1B1D"},
MatchParen = {fg = "#19191A", bg = "#7EB2DD"},
ModeMsg = {fg = "#54EDED"},
MoreMsg = {fg = "#83D28E"},
Noise = {fg = "#7F8490"},
TSPunctBracket = {link = "Noise"},
TSPunctDelimiter = {link = "Noise"},
TSTagDelimiter = {link = "Noise"},
cssAttrComma = {link = "Noise"},
cssBraces = {link = "Noise"},
cssClassNameDot = {link = "Noise"},
cssFunctionComma = {link = "Noise"},
cssSelectorOp = {link = "Noise"},
cssSelectorOp2 = {link = "Noise"},
javaScriptBraces = {link = "Noise"},
javaScriptParens = {link = "Noise"},
jsonNoise = {link = "Noise"},
pythonDot = {link = "Noise"},
["@punctuation.bracket"] = {link = "Noise"},
["@punctuation.delimiter"] = {link = "Noise"},
NonText = {fg = "#32343E"},
NormalFloat = {fg = "#4F5563", bg = "#19191A"},
Number = {fg = "#83D28E"},
javaScriptNumber = {link = "Number"},
Operator = {fg = "#F3945E"},
CtrlPBufferInd = {link = "Operator"},
CtrlPBufferNr = {link = "Operator"},
Delimiter = {link = "Operator"},
cssClassName = {link = "Operator"},
cssIdentifier = {link = "Operator"},
jinjaOperator = {link = "Operator"},
jinjaTagBlock = {link = "Operator"},
jinjaVarBlock = {link = "Operator"},
makeCommands = {link = "Operator"},
Pmenu = {fg = "#4F5563", bg = "#25262C"},
PmenuSbar = {bg = "#2D2F34"},
PmenuSel = {fg = "#19191A", bg = "#7EB2DD"},
PmenuThumb = {bg = "#4F5563"},
PreProc = {fg = "#83D28E"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
cssPseudoClass = {link = "PreProc"},
Question = {fg = "#F3945E"},
Search = {fg = "#19191A", bg = "#E7C665"},
SignColumn = {bg = "#1B1B1D"},
Special = {fg = "#9D8DC3"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
TSParameterReference = {link = "Special"},
TSTextReference = {link = "Special"},
Tag = {link = "Special"},
yamlKeyValueDelimiter = {link = "Special"},
["@parameter.reference"] = {link = "Special"},
["@text.reference"] = {link = "Special"},
SpecialKey = {fg = "#9D8DC3"},
SpellBad = {fg = "#FC5F7E", italic = true, undercurl = true},
SpellCap = {fg = "#F3945E", italic = true, undercurl = true},
SpellLocal = {fg = "#E7C665", italic = true, undercurl = true},
SpellRare = {fg = "#7EB2DD", italic = true, undercurl = true},
Statement = {fg = "#FC5F7E"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Repeat = {link = "Statement"},
TSTag = {link = "Statement"},
javaScriptFunction = {link = "Statement"},
jsonKeyword = {link = "Statement"},
yamlBlockMappingKey = {link = "Statement"},
yamlFlowMappingKey = {link = "Statement"},
StatusLine = {fg = "#4F5563", bg = "#1B1B1D"},
StatusLineDefault = {fg = "#19191A", bg = "#7EC4BE"},
StatusLineFlag = {fg = "#F3945E", bg = "#1B1B1D"},
StatusLineHighlight = {fg = "#54EDED", bg = "#1B1B1D"},
StatusLineInsert = {fg = "#19191A", bg = "#7EB2DD"},
StatusLineMid = {fg = "#7F8490", bg = "#2D2F34"},
StatusLineMidBlue = {fg = "#7EB2DD", bg = "#2D2F34"},
StatusLineMidGreen = {fg = "#83D28E", bg = "#2D2F34"},
StatusLineMidOrange = {fg = "#F3945E", bg = "#2D2F34"},
StatusLineMidPurple = {fg = "#9D8DC3", bg = "#2D2F34"},
StatusLineMidRed = {fg = "#FC5F7E", bg = "#2D2F34"},
StatusLineNC = {fg = "#4F5563", bg = "#25262C"},
StatusLineNCLight = {fg = "#32343E", bg = "#2D2F34"},
StatusLineNCMid = {fg = "#4F5563", bg = "#2D2F34"},
StatusLineNCRedFlag = {fg = "#FC5F7E", bg = "#25262C"},
StatusLineNormal = {fg = "#19191A", bg = "#FC5F7E"},
StatusLineRedFlag = {fg = "#FC5F7E", bg = "#1B1B1D"},
StatusLineReplace = {fg = "#19191A", bg = "#9D8DC3"},
BufTabLineActive = {link = "StatusLineTabActive"},
BufTabLineCurrent = {link = "StatusLineTabCurrent"},
BufTabLineHidden = {link = "StatusLineTabHidden"},
StatusLineTabModifiedActive = {fg = "#5F4448", bg = "#2D2F34"},
BufTabLineModifiedActive = {link = "StatusLineTabModifiedActive"},
StatusLineTabModifiedCurrent = {fg = "#FC5F7E", bg = "#252C37"},
BufTabLineModifiedCurrent = {link = "StatusLineTabModifiedCurrent"},
StatusLineTabModifiedHidden = {fg = "#5F4448", bg = "#111112"},
BufTabLineModifiedHidden = {link = "StatusLineTabModifiedHidden"},
StatusLineVisual = {fg = "#19191A", bg = "#F3945E"},
String = {fg = "#E7C665"},
Character = {link = "String"},
cssStringQ = {link = "String"},
pythonBuiltinType = {link = "Structure"},
["@danger"] = {link = "TSDanger"},
["@text.danger"] = {link = "TSDanger"},
["@tag"] = {link = "TSTag"},
["@tag.attribute"] = {link = "TSTagAttribute"},
["@tag.delimiter"] = {link = "TSTagDelimiter"},
TSURI = {fg = "#7EC4BE", underline = true},
TabLine = {fg = "#4F5563", bg = "#111112"},
StatusLineTabHidden = {link = "TabLine"},
TabLineFill = {fg = "#4F5563", bg = "#1B1B1D"},
BufTabLineFill = {link = "TabLineFill"},
StatusLineTabActive = {link = "TabLineFill"},
TabLineSel = {fg = "#54EDED", bg = "#252C37"},
StatusLineTabCurrent = {link = "TabLineSel"},
TelescopeBorder = {fg = "#4F5563"},
TelescopeMatching = {fg = "#7EC4BE"},
TelescopePromptPrefix = {fg = "#4F5563"},
TelescopeSelection = {bg = "#252C37"},
TelescopeSelectionCaret = {fg = "#54EDED"},
Title = {fg = "#54EDED"},
CtrlPPrtCursor = {link = "Title"},
htmlH1 = {link = "Title"},
Todo = {fg = "#F3945E", bg = "#25262C"},
Type = {fg = "#54EDED"},
CtrlPBufferCur = {link = "Type"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
Underlined = {fg = "#7EC4BE", underline = true},
VertSplit = {fg = "#25262C"},
Visual = {bg = "#40444F"},
VisualNOS = {bg = "#7F8490"},
WarningMsg = {fg = "#F3945E"},
ALEWarningSign = {link = "WarningMsg"},
StartifyNumber = {link = "WarningMsg"},
YcmWarningSign = {link = "WarningMsg"},
Whitespace = {fg = "#5F4448"},
WildMenu = {fg = "#19191A", bg = "#7EB2DD"},
YCMInverse = {fg = "#54EDED", bold = true, underline = true},
sassCssAttribute = {link = "cssAttr"},
sassClass = {link = "cssClassName"},
sassMixinName = {link = "cssFunctionName"},
sassId = {link = "cssIdentifier"},
sassProperty = {link = "cssProp"},
sassVariable = {link = "cssStringQ"},
floatBorder = {fg = "#32343E", bg = "#19191A"},
htmlBold = {bold = true},
htmlBoldItalic = {fg = "#D185B2", bold = true, italic = true},
htmlEndTag = {fg = "#5F4448"},
htmlH2 = {link = "htmlH1"},
htmlH4 = {link = "htmlH3"},
htmlH5 = {link = "htmlH4"},
htmlH6 = {link = "htmlH5"},
htmlItalic = {fg = "#D185B2", italic = true},
htmlTag = {fg = "#7F8490"},
javaScriptParensError = {link = "javaScriptError"},
jsArrowFunction = {link = "javaScriptFunction"},
jsFunction = {link = "javaScriptFunction"},
jsBuiltins = {link = "javaScriptGlobal"},
jsGlobalNodeObjects = {link = "javaScriptGlobal"},
jsGlobalObjects = {link = "javaScriptGlobal"},
jsNull = {link = "javaScriptNull"},
jsUndefined = {link = "javaScriptNull"},
jsNumber = {link = "javaScriptNumber"},
jsonBraces = {link = "jsonNoise"},
jsonKeywordMatch = {link = "jsonNoise"},
jsonQuote = {link = "jsonNoise"},
pythonBuiltInFunc = {link = "pythonBuiltin"},
pythonDecoratorName = {link = "pythonDecorator"},
pythonDottedName = {link = "pythonDecorator"},
pythonBinError = {link = "pythonError"},
pythonBytesError = {link = "pythonError"},
pythonBytesEscapeError = {link = "pythonError"},
pythonHexError = {link = "pythonError"},
pythonIndentError = {link = "pythonError"},
pythonNumberError = {link = "pythonError"},
pythonOctError = {link = "pythonError"},
pythonUniEscapeError = {link = "pythonError"},
pythonUniRawEscapeError = {link = "pythonError"},
pythonFunctionCall = {link = "pythonFunction"},
pythonBuiltinObj = {link = "pythonNull"},
pythonSingleton = {link = "pythonNull"},
["@text.uri"] = {fg = "#7EC4BE", underline = true},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='asteroid'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end

-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
--
-- This isn't strictly required but it can be a useful trick if you are
-- incrementally editing your config a lot and want to be sure your themes
-- changes are being picked up without restarting neovim.
--
-- Note if you're working in on your theme and have :Lushify'd the buffer,
-- your changes will be applied with our without the following line.
--
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
-- package.loaded['lush_theme.asteroid'] = nil

-- include our theme file and pass it to lush to apply
-- require('lush')(require('lush_theme.asteroid'))
