
local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#c5c8c6", bg = "#111112"},
TSVariable = {link = "Normal"},
["@lsp.type.variable"] = {link = "Normal"},
["@variable"] = {link = "Normal"},
ALEInfo = {fg = "#7eb2dd", bg = "#242b36"},
pythonBoolean = {link = "Boolean"},
yamlBool = {link = "Boolean"},
Builtin = {fg = "#00bcbc"},
TSFuncBuiltin = {link = "Builtin"},
TSVariableBuiltin = {link = "Builtin"},
htmlH3 = {link = "Builtin"},
javaScriptGlobal = {link = "Builtin"},
javaScriptMember = {link = "Builtin"},
jinjaBlockName = {link = "Builtin"},
jinjaFilter = {link = "Builtin"},
pythonBuiltin = {link = "Builtin"},
["@function.builtin"] = {link = "Builtin"},
["@lsp.mod.defaultLibrary"] = {link = "Builtin"},
["@variable.builtin"] = {link = "Builtin"},
CmpItemAbbrMatch = {fg = "#c5c8c6"},
CmpItemAbbrMatchFuzzy = {fg = "#4f5462"},
CmpItemKind = {fg = "#5f4448"},
CmpItemMenu = {fg = "#4e432f"},
ColorColumn = {bg = "#141415"},
Comment = {fg = "#4f5462"},
CtrlPBufferPath = {link = "Comment"},
StartifyBracket = {link = "Comment"},
StartifyPath = {link = "Comment"},
StartifySlash = {link = "Comment"},
TelescopeNormal = {link = "Comment"},
Conceal = {bg = "#2c2e34"},
Constant = {fg = "#d185b3"},
Boolean = {link = "Constant"},
CtrlPPrtText = {link = "Constant"},
Label = {link = "Constant"},
TSConstBuiltin = {link = "Constant"},
TSMath = {link = "Constant"},
htmlSpecialTagName = {link = "Constant"},
javaScriptConstant = {link = "Constant"},
javaScriptNull = {link = "Constant"},
jsonNull = {link = "Constant"},
pythonNull = {link = "Constant"},
yamlTimestamp = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
["@lsp.mod.constant"] = {link = "Constant"},
["@text.math"] = {link = "Constant"},
CtrlPLinePre = {fg = "#56eded"},
CtrlPMatch = {fg = "#56eded", bg = "#242b36"},
CtrlPMode1 = {fg = "#f39660", bg = "#141415"},
CtrlPMode2 = {fg = "#111112", bg = "#7dc3bd"},
CursorColumn = {bg = "#141415"},
CursorLine = {bg = "#141415"},
CursorLineNr = {fg = "#7eb2dd"},
pythonDecorator = {link = "Define"},
["@lsp.type.decorator"] = {link = "Define"},
DiagnosticError = {fg = "#ff3d5b"},
DiagnosticHint = {fg = "#9c8cc3"},
DiagnosticInfo = {fg = "#7eb2dd"},
DiagnosticSignError = {fg = "#ff3d5b", bg = "#141415"},
DiagnosticSignHint = {fg = "#9c8cc3", bg = "#141415"},
DiagnosticSignInfo = {fg = "#7eb2dd", bg = "#141415"},
DiagnosticSignWarn = {fg = "#f39660", bg = "#141415"},
DiagnosticUnderlineError = {fg = "#ff3d5b", bg = "#5f4448", undercurl = true},
DiagnosticUnderlineHint = {fg = "#9c8cc3", bg = "#242b36", undercurl = true},
DiagnosticUnderlineInfo = {fg = "#7eb2dd", bg = "#242b36", undercurl = true},
DiagnosticUnderlineWarn = {fg = "#f39660", bg = "#4e432f", undercurl = true},
DiagnosticWarn = {fg = "#f39660"},
DiffAdd = {fg = "#83d28d", bg = "#43634e"},
DiffChange = {fg = "#4f5462", bg = "#242b36"},
DiffDelete = {fg = "#ff3d5b", bg = "#5f4448"},
ALEError = {link = "DiffDelete"},
YcmErrorSection = {link = "DiffDelete"},
DiffText = {fg = "#f39660", bg = "#4e432f"},
ALEWarning = {link = "DiffText"},
YcmWarningSectio = {link = "DiffText"},
javaScriptDeprecated = {link = "DiffText"},
pythonSpaceError = {link = "DiffText"},
Directory = {fg = "#7eb2dd"},
ALEInfoSign = {link = "Directory"},
Error = {fg = "#ff3d5b", bg = "#242b36"},
ALEErrorSign = {link = "Error"},
CtrlPBufferCurMod = {link = "Error"},
CtrlPBufferHidMod = {link = "Error"},
CtrlPBufferVisMod = {link = "Error"},
TSDanger = {link = "Error"},
YcmErrorSign = {link = "Error"},
javaScriptError = {link = "Error"},
jsonCommentError = {link = "Error"},
jsonError = {link = "Error"},
jsonMissingCommaError = {link = "Error"},
jsonNoQuotesError = {link = "Error"},
jsonNumError = {link = "Error"},
jsonSemicolonError = {link = "Error"},
jsonStringSQError = {link = "Error"},
jsonTrailingCommaError = {link = "Error"},
jsonTripleQuotesError = {link = "Error"},
pythonError = {link = "Error"},
yamlReservedDirective = {link = "Error"},
ErrorMsg = {fg = "#ff3d5b"},
Float = {fg = "#b1d072"},
pythonBinNumber = {link = "Float"},
pythonHexNumber = {link = "Float"},
pythonOctNumber = {link = "Float"},
FoldColumn = {bg = "#141415"},
Folded = {fg = "#7eb2dd", bg = "#2c2e34"},
Function = {fg = "#7eb2dd"},
StartifyFile = {link = "Function"},
TSTagAttribute = {link = "Function"},
cssAttr = {link = "Function"},
cssFunction = {link = "Function"},
cssFunctionName = {link = "Function"},
htmlArg = {link = "Function"},
pythonFunction = {link = "Function"},
GitGutterAdd = {fg = "#83d28d", bg = "#141415"},
GitGutterChange = {fg = "#f39660", bg = "#141415"},
GitGutterChangeDelete = {fg = "#e7c664", bg = "#141415"},
GitGutterDelete = {fg = "#fc5d7c", bg = "#141415"},
HighlightSubtle = {bg = "#141415"},
Identifier = {fg = "#7dc3bd"},
StartifyFooter = {link = "Identifier"},
StartifyHeader = {link = "Identifier"},
cssProp = {link = "Identifier"},
jsDestructuringArray = {link = "Identifier"},
jsDestructuringBlock = {link = "Identifier"},
jsModuleKeyword = {link = "Identifier"},
jsObjectKey = {link = "Identifier"},
jsVariableDef = {link = "Identifier"},
yamlTagHandle = {link = "Identifier"},
yamlTagPrefix = {link = "Identifier"},
Ignore = {fg = "#33353f"},
IncSearch = {fg = "#111112", bg = "#f39660"},
CurSearch = {link = "IncSearch"},
["@punctuation.special.markdown"] = {link = "Keyword"},
LineNr = {fg = "#4f5462", bg = "#141415"},
["@lsp.typemod.macro.defaultLibrary"] = {link = "Macro"},
MatchParen = {fg = "#111112", bg = "#7eb2dd"},
ModeMsg = {fg = "#56eded"},
MoreMsg = {fg = "#83d28d"},
Noise = {fg = "#7f8490"},
TSPunctBracket = {link = "Noise"},
TSPunctDelimiter = {link = "Noise"},
TSTagDelimiter = {link = "Noise"},
cssAttrComma = {link = "Noise"},
cssBraces = {link = "Noise"},
cssClassNameDot = {link = "Noise"},
cssFunctionComma = {link = "Noise"},
cssSelectorOp = {link = "Noise"},
cssSelectorOp2 = {link = "Noise"},
javaScriptBraces = {link = "Noise"},
javaScriptParens = {link = "Noise"},
jsonNoise = {link = "Noise"},
pythonDot = {link = "Noise"},
["@punctuation.bracket"] = {link = "Noise"},
["@punctuation.delimiter"] = {link = "Noise"},
NonText = {fg = "#33353f"},
NormalFloat = {fg = "#c5c8c6", bg = "#010102"},
NormalNC = {fg = "#4f5462", bg = "#111112"},
Number = {fg = "#83d28d"},
javaScriptNumber = {link = "Number"},
Operator = {fg = "#f39660"},
CtrlPBufferInd = {link = "Operator"},
CtrlPBufferNr = {link = "Operator"},
Delimiter = {link = "Operator"},
cssClassName = {link = "Operator"},
cssIdentifier = {link = "Operator"},
jinjaOperator = {link = "Operator"},
jinjaTagBlock = {link = "Operator"},
jinjaVarBlock = {link = "Operator"},
makeCommands = {link = "Operator"},
Pmenu = {fg = "#4f5462", bg = "#25262c"},
PmenuSbar = {bg = "#2c2e34"},
PmenuSel = {fg = "#111112", bg = "#7eb2dd"},
PmenuThumb = {bg = "#4f5462"},
PreProc = {fg = "#83d28d"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
cssPseudoClass = {link = "PreProc"},
Question = {fg = "#f39660"},
Search = {fg = "#111112", bg = "#e7c664"},
SignColumn = {bg = "#141415"},
Special = {fg = "#9c8cc3"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
TSNamespace = {link = "Special"},
TSParameterReference = {link = "Special"},
TSTextReference = {link = "Special"},
Tag = {link = "Special"},
yamlKeyValueDelimiter = {link = "Special"},
["@lsp.type.namespace"] = {link = "Special"},
["@namespace"] = {link = "Special"},
["@parameter.reference"] = {link = "Special"},
["@text.reference"] = {link = "Special"},
SpecialKey = {fg = "#9c8cc3"},
SpellBad = {fg = "#fc5d7c", italic = true, undercurl = true},
SpellCap = {fg = "#f39660", italic = true, undercurl = true},
SpellLocal = {fg = "#e7c664", italic = true, undercurl = true},
SpellRare = {fg = "#7eb2dd", italic = true, undercurl = true},
Statement = {fg = "#fc5d7c"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Repeat = {link = "Statement"},
TSTag = {link = "Statement"},
javaScriptFunction = {link = "Statement"},
jsonKeyword = {link = "Statement"},
yamlBlockMappingKey = {link = "Statement"},
yamlFlowMappingKey = {link = "Statement"},
StatusLine = {fg = "#4f5462", bg = "#141415"},
StatusLineDefault = {fg = "#111112", bg = "#7dc3bd"},
StatusLineFlag = {fg = "#f39660", bg = "#141415"},
StatusLineHighlight = {fg = "#56eded", bg = "#141415"},
StatusLineInsert = {fg = "#111112", bg = "#7eb2dd"},
StatusLineMid = {fg = "#7f8490", bg = "#2c2e34"},
StatusLineMidBlue = {fg = "#7eb2dd", bg = "#2c2e34"},
StatusLineMidGreen = {fg = "#83d28d", bg = "#2c2e34"},
StatusLineMidOrange = {fg = "#f39660", bg = "#2c2e34"},
StatusLineMidPurple = {fg = "#9c8cc3", bg = "#2c2e34"},
StatusLineMidRed = {fg = "#fc5d7c", bg = "#2c2e34"},
StatusLineNC = {fg = "#4f5462", bg = "#25262c"},
StatusLineNCLight = {fg = "#33353f", bg = "#2c2e34"},
StatusLineNCMid = {fg = "#4f5462", bg = "#2c2e34"},
StatusLineNCRedFlag = {fg = "#fc5d7c", bg = "#25262c"},
StatusLineNormal = {fg = "#111112", bg = "#fc5d7c"},
StatusLineRedFlag = {fg = "#fc5d7c", bg = "#141415"},
StatusLineReplace = {fg = "#111112", bg = "#9c8cc3"},
BufTabLineActive = {link = "StatusLineTabActive"},
BufTabLineCurrent = {link = "StatusLineTabCurrent"},
BufTabLineHidden = {link = "StatusLineTabHidden"},
StatusLineTabModifiedActive = {fg = "#5f4448", bg = "#2c2e34"},
BufTabLineModifiedActive = {link = "StatusLineTabModifiedActive"},
StatusLineTabModifiedCurrent = {fg = "#fc5d7c", bg = "#242b36"},
BufTabLineModifiedCurrent = {link = "StatusLineTabModifiedCurrent"},
StatusLineTabModifiedHidden = {fg = "#5f4448", bg = "#010102"},
BufTabLineModifiedHidden = {link = "StatusLineTabModifiedHidden"},
StatusLineVisual = {fg = "#111112", bg = "#f39660"},
String = {fg = "#e7c664"},
Character = {link = "String"},
cssStringQ = {link = "String"},
pythonBuiltinType = {link = "Structure"},
["@lsp.typemod.class.defaultLibrary"] = {link = "Structure"},
["@danger"] = {link = "TSDanger"},
["@text.danger"] = {link = "TSDanger"},
["@tag"] = {link = "TSTag"},
["@tag.attribute"] = {link = "TSTagAttribute"},
["@tag.delimiter"] = {link = "TSTagDelimiter"},
TSURI = {fg = "#7dc3bd", underline = true},
TabLine = {fg = "#4f5462", bg = "#010102"},
StatusLineTabHidden = {link = "TabLine"},
TabLineFill = {fg = "#4f5462", bg = "#141415"},
BufTabLineFill = {link = "TabLineFill"},
StatusLineTabActive = {link = "TabLineFill"},
TabLineSel = {fg = "#56eded", bg = "#242b36"},
StatusLineTabCurrent = {link = "TabLineSel"},
TelescopeBorder = {fg = "#4f5462"},
TelescopeMatching = {fg = "#7dc3bd"},
TelescopePromptPrefix = {fg = "#4f5462"},
TelescopeSelection = {bg = "#242b36"},
TelescopeSelectionCaret = {fg = "#56eded"},
Title = {fg = "#56eded"},
CtrlPPrtCursor = {link = "Title"},
htmlH1 = {link = "Title"},
Todo = {fg = "#f39660", bg = "#25262c"},
Type = {fg = "#56eded"},
CtrlPBufferCur = {link = "Type"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
Underlined = {fg = "#7dc3bd", underline = true},
VertSplit = {fg = "#25262c"},
Visual = {bg = "#414550"},
VisualNOS = {bg = "#7f8490"},
WarningMsg = {fg = "#f39660"},
ALEWarningSign = {link = "WarningMsg"},
StartifyNumber = {link = "WarningMsg"},
YcmWarningSign = {link = "WarningMsg"},
Whitespace = {fg = "#5f4448"},
WildMenu = {fg = "#111112", bg = "#7eb2dd"},
YCMInverse = {fg = "#56eded", bold = true, underline = true},
sassCssAttribute = {link = "cssAttr"},
sassClass = {link = "cssClassName"},
sassMixinName = {link = "cssFunctionName"},
sassId = {link = "cssIdentifier"},
sassProperty = {link = "cssProp"},
sassVariable = {link = "cssStringQ"},
floatBorder = {fg = "#33353f", bg = "#111112"},
htmlBold = {bold = true},
htmlBoldItalic = {fg = "#d185b3", bold = true, italic = true},
htmlEndTag = {fg = "#5f4448"},
htmlH2 = {link = "htmlH1"},
htmlH4 = {link = "htmlH3"},
htmlH5 = {link = "htmlH4"},
htmlH6 = {link = "htmlH5"},
htmlItalic = {fg = "#d185b3", italic = true},
htmlTag = {fg = "#7f8490"},
javaScriptParensError = {link = "javaScriptError"},
jsArrowFunction = {link = "javaScriptFunction"},
jsFunction = {link = "javaScriptFunction"},
jsBuiltins = {link = "javaScriptGlobal"},
jsGlobalNodeObjects = {link = "javaScriptGlobal"},
jsGlobalObjects = {link = "javaScriptGlobal"},
jsNull = {link = "javaScriptNull"},
jsUndefined = {link = "javaScriptNull"},
jsNumber = {link = "javaScriptNumber"},
jsonBraces = {link = "jsonNoise"},
jsonKeywordMatch = {link = "jsonNoise"},
jsonQuote = {link = "jsonNoise"},
pythonBuiltInFunc = {link = "pythonBuiltin"},
pythonDecoratorName = {link = "pythonDecorator"},
pythonDottedName = {link = "pythonDecorator"},
pythonBinError = {link = "pythonError"},
pythonBytesError = {link = "pythonError"},
pythonBytesEscapeError = {link = "pythonError"},
pythonHexError = {link = "pythonError"},
pythonIndentError = {link = "pythonError"},
pythonNumberError = {link = "pythonError"},
pythonOctError = {link = "pythonError"},
pythonUniEscapeError = {link = "pythonError"},
pythonUniRawEscapeError = {link = "pythonError"},
pythonFunctionCall = {link = "pythonFunction"},
pythonBuiltinObj = {link = "pythonNull"},
pythonSingleton = {link = "pythonNull"},
["@lsp.mod.deprecated"] = {fg = "#4e432f"},
["@text.uri"] = {fg = "#7dc3bd", underline = true},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='asteroid'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end

-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
--
-- This isn't strictly required but it can be a useful trick if you are
-- incrementally editing your config a lot and want to be sure your themes
-- changes are being picked up without restarting neovim.
--
-- Note if you're working in on your theme and have :Lushify'd the buffer,
-- your changes will be applied with our without the following line.
--
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
-- package.loaded['lush_theme.asteroid'] = nil

-- include our theme file and pass it to lush to apply
-- require('lush')(require('lush_theme.asteroid'))
