# BASE UI
Normal: 'fg bg'
ColorColumn: '. dark0'
Conceal: '. dark2'

Cursor: ''
CursorIM: ''
CursorColumn: '. dark1'
CursorLine: '. dark1'

Directory: 'lightblue'

DiffAdd: 'green dullgreen'
DiffChange: 'light2 dullblue'
DiffDelete: 'red dullred'
DiffText: 'orange dullyellow'

ErrorMsg: 'red'
VertSplit: 'dark1'
Folded: 'lightblue dark2'
FoldColumn: '. dark0'
SignColumn: '. dark0'

IncSearch: 'bg orange'
Search: 'bg yellow'

LineNr: 'light1 dark0'
CursorLineNr: 'light2'
MatchParen: 'bg lightblue'
ModeMsg: 'cyan'
MoreMsg: 'green'
NonText: 'light1'

Pmenu: 'light2 dark1'
PmenuSel: 'bg lightblue'
PmenuSbar: '. dark2'
PmenuThumb: '. light2'

Question: 'orange'
SpecialKey: 'purple'

SpellBad: 'red . u'
SpellLocal: 'orange . u'
SpellCap: 'yellow . u'
SpellRare: 'lightblue . u'

TabLine: 'light2 darkest'
TabLineFill: 'light2 dark0'
TabLineSel: 'cyan dullblue'

Title: 'cyan'
Visual: '. selection'
VisualNOS: '. light3'
WarningMsg: 'orange'
WildMenu: 'bg lightblue'

# BASE SYNTAX
Comment: 'light2'
Builtin: 'aqua'
Noise: 'light3'

Constant: 'pink'
String: 'yellow' # Constant
Character: '@String' # Constant
Boolean: '@Constant' # Constant
Number: 'green' # Constant
Float: 'olivegreen' # Constant

Identifier: 'blue'
Function: 'lightblue' # Identifier

Statement: 'red'
Conditional: '@Statement' # Statement
Repeat: '@Statement' # Statement
Label: '@Statement' # Statement
Operator: 'orange' # Statement
Keyword: '@Statement' # Statement
Exception: '@Statement' # Statement

PreProc: 'green'
Include: '@PreProc' # PreProc
Define: '@PreProc' # PreProc
Macro: '@PreProc' # PreProc
PreCondit: '@PreProc' # PreProc

Type: 'cyan'
StorageClass: '@Type' # Type
Structure: '@Type' # Type
Typedef: '@Type' # Type

Special: 'purple'
SpecialChar: '@Special' # Special
Tag: '@Special' # Special
Delimiter: '@Operator' # Special
SpecialComment: '@Special' # Special
Debug: '@Constant' # Special

Underlined: 'blue . u'
Ignore: 'light1'
Error: 'red'
Todo: 'orange'
